# Generated by Django 5.2.8 on 2025-12-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(choices=[('Norte', 'Norte'), ('Sur', 'Sur'), ('Centro', 'Centro'), ('Internacional', 'Internacional')], max_length=50)),
                ('peso_minimo', models.FloatField()),
                ('peso_maximo', models.FloatField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
